UwUMaker-c-sources-y += main.c stat_printer.c
# UwUMaker-c-flags-y += -fsanitize=address
# UwUMaker-linker-flags-y += -fsanitize=address
# UwUMaker-c-flags-y += -fsanitize=undefined
# UwUMaker-linker-flags-y += -fsanitize=undefined

UwUMaker-always-subprojects-y += exe
