
UwUMaker-c-flags-y += -I$(ROOT_PROJECT_DIR)/src/test
UwUMaker-c-flags-y += -I$(ROOT_PROJECT_DIR)/src/
UwUMaker-c-sources-y += main.c

UwUMaker-shared-lib-subprojects-y += $(ROOT_PROJECT_DIR)

UwUMaker-name := FluffyGCTest
UwUMaker-is-executable := y

