UwUMaker-c-sources-y += context.c profiler.c bitops.c managed_heap.c panic.c

UwUMaker-dirs-y += util object gc \
	memory concurrency itc rcu logger \
	stacktrace api hook

UwUMaker-dirs-$(CONFIG_FUZZER) += fuzzing

