UwUMaker-c-sources-$(CONFIG_FUZZ_SOC) += fuzzing_soc.c
UwUMaker-c-sources-$(CONFIG_FUZZ_HEAP) += fuzzing_heap.c
UwUMaker-c-sources-$(CONFIG_FUZZ_ROOT_REFS) += fuzzing_root_refs.c

UwUMaker-dirs-$(CONFIG_FUZZER_LIBFUZZER) += variant

